steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - --no-cache
      - --pull
      - -f
      - Containerfile
      - -t
      - gcr.io/$PROJECT_ID/jira-asana-sync:$SHORT_SHA
      - -t
      - gcr.io/$PROJECT_ID/jira-asana-sync:latest
      - .
images:
  - gcr.io/$PROJECT_ID/jira-asana-sync:$SHORT_SHA
  - gcr.io/$PROJECT_ID/jira-asana-sync:latest
options:
  logging: CLOUD_LOGGING_ONLY
