apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jira-asana-sync-state
  namespace: jira-asana-sync
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard-rwo
